### ISSUE TITLE
Boleh Bantuin?

### ISSUE THREAD

**Issue by NoXLaw** [darkGrimoire/6-auto-purezento#11]
Kak, saya dari kampus lain selain kampus ITB kakak, tapi saya pengen buat bot auto presensi seperti ITB..
dan saya membuat nya dengan acuan git kakak, bisa nggak kak bantuin untuk ngebuatnya?
hampir jadi tapi selalu error, entah kenapa error nya, jika ingin membantu balass donk kak, hehe
nanti tak kasih source nya

**Comment by darkGrimoire** [comment]
Halo, boleh bisa kirim ke email di profil saya ya nanti kubales dgn kontak yg lebih enak buat diskusi hehe
